version: '3.6'

services:
    db:
      restart: always
      image: mysql/mysql-server:5.7.28
      container_name: mlflow_db
      expose:
        - "3306"
      networks:
        - backend
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - dbdata:/var/lib/mysql

    jupyter:
        build: ./jupyter
        image: jupyter_lab
        networks:
          - frontend
          - backend
        environment:
          - JUPYTER_TOKEN=easy
        ports:
          - "8888:8888"
          - "5000:5000"
        volumes:
          - /mnt/data/jupyter/solipsisai:/home/jovyan/work
          - /mnt/data/mlruns:/mnt/data
        command: start-notebook.sh --NotebookApp.token=${JUPYTER_PASSWORD}
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]

    nginx:
        restart: always
        build: ./nginx
        image: mlflow_nginx
        container_name: mlflow_nginx
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - jupyter

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    dbdata:
